// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SilvItemLog","status":true,"description":"v1.08 Item Log. Displays the last looted items.\r\n<SilverItemLog>","parameters":{"-- General --":"","Auto Gain Loot":"true","Auto Log Items":"true","-- Sound --":"","Default Volume":"-1","Default Pitch":"100","Item SFX":"Item1","Gold SFX":"Coin","-- Positioning & Size --":"","Window X":"-2","Window Y":"2","Window Horizontal Alignment":"Right","Window Vertical Alignment":"Top","Window Width":"400","Window Height":"160","-- Window Contents --":"","Font Size":"24","Text Offset X":"10","Text Offset Y":"6","Standard Padding":"0","Positive Prefix Text":"获得","Negative Prefix Text":"失去","Icon Y-offset":"4","Window Skin":"Window_ItemLog","Auto-clear Upon Full-fade":"false","-- Miscellaneous --":"","Fadeout Delay":"240","Fadeout Speed":"2","Text Shading":"-0.15","Gold IconIndex":"163"}}
];
